workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /(\[skip ci\])/i'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /Merge branch '(v|rc)\/.+'/
      when: always
      variables:
        PIPELINE_TYPE: release

.release_rule: # Run when release branch merged to default branch
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /Merge branch '(v|rc)\/.+'/
      when: always

.get_version: &get_version # Define current version
  - export NAME=$(grep -m 1 '"name"' package.json | cut -d '"' -f 4)
  - echo "NAME=$NAME" >> build.env
  - export VERSION=$(grep -m 1 '"version"' package.json | cut -d '"' -f 4)
  - echo "VERSION=$VERSION" >> build.env
  - export BUILD_VERSION=$( [[ ${PIPELINE_TYPE} == 'release' ]] && echo ${VERSION} || echo ${VERSION}-dev-${CI_PIPELINE_IID} )
  - echo "BUILD_VERSION=$BUILD_VERSION" >> build.env
  - echo "variables PIPELINE_TYPE=$PIPELINE_TYPE BUILD_VERSION=$BUILD_VERSION"

.dependencies_cache: # Cache node_modules between stages/jobs
  cache:
    key:
      prefix: $CI_COMMIT_BRANCH
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull

image: node:20
default:
  tags:
    - k8s-gitlab-runner

variables:
  PACKAGE_MANAGER: yarn
  PIPELINE_TYPE: snapshot
  PUBLISH_PACKAGE: true

install_dependencies:
  extends: .dependencies_cache
  stage: .pre
  before_script:
    - cp $LP_NPMRC_FILE ~/.npmrc
  script:
    - $PACKAGE_MANAGER install --no-audit --pure-lockfile
  # Redefine cache to have default pull-push policy
  cache:
    policy: pull-push

stages:
  - test
  - build
  - e2e
  - deploy
  - release

lint:
  extends: .dependencies_cache
  stage: test
  script:
    - yarn lint

test:
  extends: .dependencies_cache
  needs: [build]
  stage: e2e
  script:
    - yarn test
  artifacts:
    when: always
    reports:
      junit: junit.xml

build:
  extends: .dependencies_cache
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - ./dist
    expire_in: 1h

release-set-version:  # Workaround to pass variables # https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-release-metadata-in-a-custom-script
  stage: .pre
  rules:
    - !reference [.release_rule, rules]
  script:
    - *get_version
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env

release-npm: # Publish the package to LP NPM registry
  extends: .dependencies_cache
  stage: release
  needs: [build]
  rules:
    - !reference [.release_rule, rules]
  script:
    - |
      cp $LP_NPMRC_FILE ~/.npmrc
      $PACKAGE_MANAGER pack
      $PACKAGE_MANAGER publish --non-interactive
  artifacts:
    paths:
      - '*.tgz'
    expire_in: never

release: # Create a release when a release is merged to the default branch https://docs.gitlab.com/ee/ci/yaml/#release
  stage: release
  needs:
    - build
    - job: release-set-version
      artifacts: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - !reference [.release_rule, rules]
  script:
    - echo "Prepare release ${NAME} v${VERSION}"
  release:
    name: 'Release ${NAME} v${VERSION}'
    tag_name: 'v${VERSION}'
    description: 'CI pipeline release new tag v${VERSION}'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: "${NAME}-${VERSION}.tgz"
          url: "https://artifactory.dev.int.gw.lpcloud.io/ui/api/v1/download?repoKey=lp-npm-local-FROM-CA&path=${NAME}/-/${NAME}-${VERSION}.tgz"
          link_type: "package"

pages: # Publish Docs/Playground when a release is merged to the default branch https://docs.gitlab.com/ee/ci/yaml/#release
  extends: .dependencies_cache
  stage: deploy
  needs: [build]
  rules:
    - !reference [.release_rule, rules]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
  script:
    - $PACKAGE_MANAGER build:docs
    - echo "Pages deployment accessible through ${CI_PAGES_URL}/${CI_COMMIT_BRANCH}"
  pages:
    path_prefix: "$CI_COMMIT_BRANCH"
  artifacts:
    paths:
      - public